FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY .npmrc package.json package-lock.json tsconfig.json ./
RUN npm ci
COPY src ./src
RUN npx tsc --project tsconfig.json
RUN npm prune --omit=dev

FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

EXPOSE 2525 8080
ENTRYPOINT ["node", "dist/mailroom/entry.js"]
